# Translation-cell (unit-cell motif) layer.
#
# This layer describes a lattice by its *fundamental domain* — a finite
# set of basis sites and a finite bond motif — together with a
# translation action, instead of by an enumerated `1:num_sites` site
# list. It is the substrate for building tensor networks in the
# thermodynamic limit: place one tensor per site orbit and one per bond
# orbit, then contract according to the motif. No site is ever
# materialised; every concrete site/bond is computed on demand.
#
# The same interface serves finite (OBC/PBC) and truly infinite
# lattices: finiteness and boundary conditions only change how the
# motif is *tiled*, not the motif itself. A downstream TN builder that
# is written against `site_orbits` / `bond_orbits` works unchanged
# across `FiniteSize` and `InfiniteSize` lattices.

# ---- Concrete site / bond identities ---------------------------------

"""
    CellSite{D}(cell::SVector{D, Int}, basis::Int)

A single site of a translationally invariant lattice, addressed by its
unit-cell coordinate `cell ∈ ℤ^D` and its basis index `basis` within
the cell. This is the site identity used by the lazy accessors
([`neighbors_at`](@ref), [`cell_position`](@ref)) — an infinite lattice
has no linear `1:num_sites` index, so sites are named by coordinate
instead.
"""
struct CellSite{D}
    cell::SVector{D,Int}
    basis::Int
end

# The 2-arg `CellSite(::SVector{D,Int}, ::Int)` form is auto-generated by
# the struct definition; we only add the tuple conversion and the
# `basis = 1` defaults.
function CellSite(cell::NTuple{D,Int}, basis::Int=1) where {D}
    return CellSite{D}(SVector{D,Int}(cell), basis)
end
CellSite(cell::SVector{D,Int}) where {D} = CellSite{D}(cell, 1)

"""
    CellBond{D}(src::Int, dst::Int, offset::SVector{D, Int}, type::Symbol)

A bond of the unit-cell motif. It connects basis site `src` in the
home cell to basis site `dst` in the cell displaced by `offset` (target
cell `= home cell + offset`). `type` is a dispatch tag (e.g.
`:nearest`).

By convention, each *undirected* bond of the lattice should appear
exactly once in the motif returned by [`cell_bonds`](@ref) — this is
the implementer's responsibility and is **not** validated. Listing a
bond twice (e.g. both `(1, 1, (1, 0))` and `(1, 1, (-1, 0))`) would
double-count neighbours. The lazy accessor [`incident_cell_bonds`](@ref)
re-anchors motif bonds to a requested site, orienting them outward from
that site.
"""
struct CellBond{D}
    src::Int
    dst::Int
    offset::SVector{D,Int}
    type::Symbol
end

function CellBond(
    src::Int, dst::Int, offset::NTuple{D,Int}, type::Symbol=:nearest
) where {D}
    return CellBond{D}(src, dst, SVector{D,Int}(offset), type)
end

# ---- Translation-cell interface (generic functions) ------------------

"""
    translation_vectors(lat::AbstractLattice{D, T}) → SMatrix{D, D, T}

The Bravais translation vectors of `lat`, as the columns of a `D×D`
matrix. A unit-cell coordinate `cell ∈ ℤ^D` maps to the real-space
cell origin `translation_vectors(lat) * cell`.

Concrete translationally invariant lattices must implement this. It has
no universal default because the geometry is lattice-specific.
"""
function translation_vectors end

"""
    num_basis_sites(lat::AbstractLattice) → Int

Number of sites in one unit cell (the size of the site motif). Defaults
to [`num_sublattices`](@ref), which is `1` unless the lattice is
sublattice-aware.
"""
num_basis_sites(lat::AbstractLattice) = num_sublattices(lat)

"""
    basis_position(lat::AbstractLattice{D, T}, b::Int) → SVector{D, T}

Real-space offset of basis site `b` relative to its cell origin. The
default places a single basis site at the origin; multi-basis lattices
(honeycomb, kagome, ...) must override.
"""
function basis_position(lat::AbstractLattice{D,T}, b::Int) where {D,T}
    if b == 1
        return zero(SVector{D,T})
    end
    return throw(
        ArgumentError(
            "basis_position: $(typeof(lat)) has an unspecified basis site $b; " *
            "override `basis_position` for multi-basis lattices",
        ),
    )
end

"""
    cell_bonds(lat::AbstractLattice) → iterator of CellBond{D}

The bond motif: a finite iterator of [`CellBond`](@ref), which by
convention lists each undirected bond of the lattice exactly once (see
[`CellBond`](@ref) for the double-counting caveat). This is the bond
analogue of the site basis and the key object for placing bond tensors
in the thermodynamic limit.

Concrete translationally invariant lattices must implement this.
"""
function cell_bonds end

# ---- Orbit accessors (uniform across finite / infinite) --------------

"""
    site_orbits(lat::AbstractLattice) → iterator

Representatives of the site orbits under the translation group — i.e.
the basis sites `1:num_basis_sites(lat)`. A TN builder places one site
tensor per element of this iterator regardless of the lattice's size or
boundary condition.
"""
site_orbits(lat::AbstractLattice) = 1:num_basis_sites(lat)

"""
    bond_orbits(lat::AbstractLattice) → iterator of CellBond{D}

Representatives of the bond orbits under the translation group. Defaults
to [`cell_bonds`](@ref). A TN builder places one bond tensor per
element of this iterator.
"""
bond_orbits(lat::AbstractLattice) = cell_bonds(lat)

# ---- Lazy concrete access (computed on demand, nothing enumerated) ---

"""
    cell_position(lat::AbstractLattice{D, T}, cell, b::Int=1) → SVector{D, T}

Real-space position of basis site `b` in unit cell `cell` (an
`NTuple{D,Int}`, `SVector{D,Int}`, or [`CellSite`](@ref)), computed as
`translation_vectors(lat) * cell + basis_position(lat, b)`. Works for
any cell coordinate — including cells far outside any finite sample —
without materialising the lattice.
"""
function cell_position(
    lat::AbstractLattice{D,T}, cell::SVector{D,Int}, b::Int=1
) where {D,T}
    return translation_vectors(lat) * SVector{D,T}(cell) + basis_position(lat, b)
end
function cell_position(lat::AbstractLattice{D}, cell::NTuple{D,Int}, b::Int=1) where {D}
    return cell_position(lat, SVector{D,Int}(cell), b)
end
cell_position(lat::AbstractLattice, s::CellSite) = cell_position(lat, s.cell, s.basis)

"""
    incident_cell_bonds(lat::AbstractLattice, s::CellSite) → Vector{CellBond}

The bonds incident to site `s`, each re-anchored so that `src` is
`s.basis` and `offset` points from `s.cell` toward the neighbour's
cell. Every motif bond contributes in both orientations (once where `s`
plays the motif `src`, once where it plays the motif `dst`), so a site
sees its full coordination shell. Computed lazily from
[`cell_bonds`](@ref); no global bond list is built.
"""
function incident_cell_bonds(lat::AbstractLattice{D}, s::CellSite{D}) where {D}
    nb = num_basis_sites(lat)
    1 <= s.basis <= nb || throw(
        ArgumentError("CellSite basis $(s.basis) is out of range 1:$nb for $(typeof(lat))"),
    )
    out = CellBond{D}[]
    for cb in cell_bonds(lat)
        if cb.src == s.basis
            push!(out, CellBond{D}(cb.src, cb.dst, cb.offset, cb.type))
        end
        # The reverse orientation: s sits at the motif `dst` end. Skip the
        # degenerate self-loop (same basis, zero offset) to avoid listing
        # it twice.
        if cb.dst == s.basis && !(cb.src == cb.dst && iszero(cb.offset))
            push!(out, CellBond{D}(cb.dst, cb.src, -cb.offset, cb.type))
        end
    end
    return out
end

"""
    neighbors_at(lat::AbstractLattice, s::CellSite) → Vector{CellSite}

The neighbouring sites of `s`, computed on demand from the bond motif.
This is the infinite-lattice analogue of [`neighbors`](@ref): it works
for any cell coordinate and never requires the lattice to be finite or
materialised.
"""
function neighbors_at(lat::AbstractLattice{D}, s::CellSite{D}) where {D}
    return [CellSite{D}(s.cell + cb.offset, cb.dst) for cb in incident_cell_bonds(lat, s)]
end

# ---- Element centring on the fundamental domain (orbits) ------------
#
# The [`AbstractLatticeElement`](@ref) centring trait — `VertexCenter` /
# `BondCenter` / `PlaquetteCenter` — applied at the *orbit* level: one
# representative per translation orbit, plus its real-space
# representative position. Unlike the enumeration API
# (`elements` / `element_position`, which walk `1:num_sites` / `bonds` /
# `plaquettes`), these read the finite fundamental domain and so are
# defined for infinite lattices — the geometry substrate for attaching
# one degree of freedom per site / bond / plaquette orbit in the
# thermodynamic limit.

"""
    plaquette_orbits(lat::AbstractLattice) → iterator of PlaquetteRule

Representatives of the plaquette (face) orbits under the translation
group — the unit cell's `PlaquetteRule`s. Defaults to `()` (lattices
with no plaquette notion). The bond / site analogues are
[`bond_orbits`](@ref) / [`site_orbits`](@ref).
"""
plaquette_orbits(::AbstractLattice) = ()

"""
    element_orbits(lat::AbstractLattice, e::AbstractLatticeElement)

Representatives of the orbits of centring `e` under the translation
group: [`site_orbits`](@ref) for [`VertexCenter`](@ref),
[`bond_orbits`](@ref) for [`BondCenter`](@ref), and
[`plaquette_orbits`](@ref) for [`PlaquetteCenter`](@ref). A finite
fundamental domain — defined for infinite lattices, where the
enumeration `elements` is not.
"""
element_orbits(lat::AbstractLattice, ::VertexCenter) = site_orbits(lat)
element_orbits(lat::AbstractLattice, ::BondCenter) = bond_orbits(lat)
element_orbits(lat::AbstractLattice, ::PlaquetteCenter) = plaquette_orbits(lat)

"""
    element_orbit_position(lat, e::AbstractLatticeElement, rep) → SVector{D,T}

Real-space position of an orbit representative `rep` of centring `e`,
evaluated on the home unit cell via [`cell_position`](@ref):

- [`VertexCenter`](@ref), `rep::Int` (basis index) → the basis-site
  position;
- [`BondCenter`](@ref), `rep::`[`CellBond`](@ref) → the midpoint of the
  bond's two endpoints;
- [`PlaquetteCenter`](@ref), `rep::PlaquetteRule` → the centroid of its
  corner sites.

Consistent with [`bond_center`](@ref) / `plaquette_center`, but
evaluated on the fundamental domain: it needs no boundary wrapping (the
motif carries unwrapped cell offsets) and works for infinite lattices.
"""
function element_orbit_position(
    lat::AbstractLattice{D,T}, ::VertexCenter, b::Int
) where {D,T}
    return cell_position(lat, zero(SVector{D,Int}), b)
end

function element_orbit_position(
    lat::AbstractLattice{D,T}, ::BondCenter, cb::CellBond{D}
) where {D,T}
    p_src = cell_position(lat, zero(SVector{D,Int}), cb.src)
    p_dst = cell_position(lat, cb.offset, cb.dst)
    return (p_src + p_dst) / 2
end

function element_orbit_position(
    lat::AbstractLattice{2,T}, ::PlaquetteCenter, pr::PlaquetteRule
) where {T}
    acc = zero(SVector{2,T})
    for (sub, dx, dy) in pr.corners
        acc += cell_position(lat, SVector{2,Int}(dx, dy), sub)
    end
    return acc / length(pr.corners)
end
